### ISSUE TITLE
provide a place for testing and development scripts

### ISSUE THREAD

**Issue by setempler** [mpg-age-bioinformatics/AGEpy#1]
@jorgeboucas 

In my understanding, any folder that is _not conflicting with the build process_ (e.g. `build` or `*egg`) and _not mentioned as a module_ in `setup.py` can exist without problems.

The testing example in https://python-packaging.readthedocs.org/en/latest/index.html  is only one of many possibilities. I don't like it (yet) for this project, since there test units are a) defined within module subfolders and b) depend on an additional package `nose` and c) do not comprise build/develop scripts.

Django uses BASE/tests/ and other folders, too, for example. See https://github.com/django/django.

Please provide a folder for such scripts. Thanks.

**Comment by jorgeboucas** [comment]
internal git
