### ISSUE TITLE
david: split gene ids (merged from cufflinks)

### ISSUE THREAD

**Issue by setempler** [mpg-age-bioinformatics/AGEpy#4]
Add option `--split-id SEPARATOR`:
- split and expand gene list values by the supplied separator if `-g` option is used
- default `None` means no splitting
- problem/use case: cufflinks creates merged XLOC, thus merged gene symbols, which are not matching gtf file `gene_name`s

See also https://github.com/mpg-age-bioinformatics/htseq-tools/blob/master/aDiff

**Comment by jorgeboucas** [comment]
use XLOC to retrieved old gene id

**Comment by setempler** [comment]
XLOC can contain list of genes.

So, for one XLOC

1) **split list and duplicate lines per element?**

e.g. 

```
gene_id     log2fc pvalue
geneA;geneB 3.1    0.034
```

to

```
gene_id log2fc pvalue
geneA   3.1    0.034
geneB   3.1    0.034
```

or

2) **use first gene only (as aDiff did)?**

**Comment by jorgeboucas** [comment]
do 1)  as aDiff does.
