### ISSUE TITLE
david: implement gene statistics list

### ISSUE THREAD

**Issue by setempler** [mpg-age-bioinformatics/AGEpy#5]
- Implement option `--stats-column N` to extract statistics for each gene, and merge this as list in the enrichment output (e.g. differential gene expression log fold changes). 
- Requires `--column`
- Use case: cellplot

**Comment by jorgeboucas** [comment]
for cell plot we would go for the fold change of the gene, and the enrichment and stats value of the term (not the gene)

**Comment by setempler** [comment]
this is what I meant (gene stat = logFC of DEG, others like p-values of DEG...), in relation to a DEG table as input

**Comment by setempler** [comment]
done, see 93d8eb0e15d20a73ad26ef52b569cd7c6b71fc6a
