### ISSUE TITLE
david: implement background gene list

### ISSUE THREAD

**Issue by setempler** [mpg-age-bioinformatics/AGEpy#6]
- supply a table with list of 

requires 
- single file for all input tables to analyse or sequential along input tables (same amount of files)
- `--background-table FILE` to specify file
- `--background-column N` to specify column
- `--background-sheet SHEET` to specify sheet

**Comment by jorgeboucas** [comment]
we don't need all this options, see DTC, thus there was a working script on the internal repo that if anything just needed to go on using the functions in the AGEpy package.

**Comment by setempler** [comment]
This option was already part of DTC, from which david is an extended copy of. You recently deleted the lines from the DTC function 'DAVIDit' which I planned to take the 'background feature' from.

DTC is not sufficient to deal with other input formats than gene lists per columns. E.g. a DEG table.
